apiVersion: v1
kind: Secret
metadata:
  name: employee-stock-api-secrets
type: Opaque
data:
  # Base64 encoded secrets
  # Example: echo -n "your-secret-key" | base64
  jwt-secret: ${JWT_SECRET_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: employee-stock-api-aws-secrets
type: Opaque
data:
  # Base64 encoded AWS credentials
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID_BASE64}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY_BASE64}
  S3_LOG_BUCKET: ${S3_LOG_BUCKET_BASE64}