apiVersion: v1
kind: Service
metadata:
  name: employee-stock-api
  labels:
    app: employee-stock-api
spec:
  selector:
    app: employee-stock-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: ClusterIP